on:
  push:
    tags:
      - "v*.*.*"
name: Release
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: make test
  build-release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: make build
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "bin/connectionWatcher"
          token: ${{ secrets.GITHUB_TOKEN }}